// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQvvW9KZmKEMBVXqbKXGPRAL1xyLfHkY',
    appId: '1:957479354422:web:471f87c2c476690f891897',
    messagingSenderId: '957479354422',
    projectId: 'fir-ef46b',
    authDomain: 'fir-ef46b.firebaseapp.com',
    storageBucket: 'fir-ef46b.firebasestorage.app',
    measurementId: 'G-E8JKF9SNHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENYnAeUeSR9dNAcUpDmxdepyjFyolGXE',
    appId: '1:957479354422:android:ec5f16fb0a366b49891897',
    messagingSenderId: '957479354422',
    projectId: 'fir-ef46b',
    storageBucket: 'fir-ef46b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0HsyQmRapPKt5v4yzjfHiB_cbVK5ffAk',
    appId: '1:957479354422:ios:5838247c92a904af891897',
    messagingSenderId: '957479354422',
    projectId: 'fir-ef46b',
    storageBucket: 'fir-ef46b.firebasestorage.app',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0HsyQmRapPKt5v4yzjfHiB_cbVK5ffAk',
    appId: '1:957479354422:ios:5838247c92a904af891897',
    messagingSenderId: '957479354422',
    projectId: 'fir-ef46b',
    storageBucket: 'fir-ef46b.firebasestorage.app',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJQvvW9KZmKEMBVXqbKXGPRAL1xyLfHkY',
    appId: '1:957479354422:web:fb0edf5842df108a891897',
    messagingSenderId: '957479354422',
    projectId: 'fir-ef46b',
    authDomain: 'fir-ef46b.firebaseapp.com',
    storageBucket: 'fir-ef46b.firebasestorage.app',
    measurementId: 'G-6GFNXJJFKX',
  );
}
